### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LuantistDork** [interactions-py/interactions.py#1052]
### Describe the bug.

I was just programming my bot, adding a new command. (on repl.it)
but when I tried to run it, I got this gnarly error:
```
Traceback (most recent call last):
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/interactions/api/http/request.py", line 152, in request
    data = await response.json(content_type=None)
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    bot = interactions.Client(token=token)
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/interactions/client/bot.py", line 115, in __init__
    self.me = Application(**data, _client=self._http)
TypeError: type object argument after ** must be a mapping, not NoneType
```
here's my `main.py`:
```py
import os
from shortcuts import *
import wikipedia
import interactions
from discord.ext.commands import has_permissions, MissingPermissions
from keep_alive import keep_alive
import json
import asyncio
import time

token = os.getenv("token")
bot = interactions.Client(token=token)
second = 0


### ADMIN COMMANDS ###

# PURGE COMMAND #
@bot.command(
    name="purge",
    description="Delete messages in the current channel",
)
@interactions.option(
    name="count",
    description="The amount of messages you want to delete",
    type=interactions.OptionType.STRING,
    required=True,
)
@has_permissions(manage_messages=True)
async def purge(ctx: interactions.context, count: str):
    channel = await ctx.get_channel()
    has_perms = ctx.author.permissions
    if not (has_perms.MANAGE_MESSAGES or has_perms.ADMINISTRATOR or has_perms.ALL):
        await ctx.send(content="You don't have permission to do that", ephemeral=True)
        return
    try:    
        msgs = await ctx.channel.purge(int(count))
        await ctx.send(content="Purged {0} messages".format(len(msgs)), ephemeral=True)
    except:
        await ctx.send(content="The `count` argument must be a number!")

### GET COMMANDS ###

## WIKIPEDIA COMMANDS ##

# WIKIPEDIA COMMAND #
@bot.command(
    name="wikipedia"
)
async def wiki(ctx):
    pass

@wiki.subcommand(
    name="get",
)
@interactions.option(
    name="title",
    description="The title of the wikipedia article",
    type=interactions.OptionType.STRING,
    required=True,
)
@interactions.option(
    name="hide",
    description="When true, only you will see the response",
    type=interactions.OptionType.BOOLEAN,
    required=False,
)
async def wikiget(ctx: interactions.CommandContext, title: str, hide: bool = False): 
    """Get a wikipedia page by title"""
    search = wikipedia.search(title)
    print(search)
    if search is None:
        await ctx.send(
            content="No results found for \"{0}\"".format(title),
            ephemeral=hide
        )
        return
    title = search[0]
    try:    
        a = wikipedia.page(
            title=title,
            auto_suggest=False
        )
    except Exception as e:
        await ctx.send("{0}".format(str(e).replace("`", "\\`")))
        return
        
    embed = wiki2embed(a)    
    await ctx.send(
        embeds=[embed],
        ephemeral=hide
    )
    return
        
# RANDWIKI COMMAND #
@wiki.subcommand(
    name="random",
    description="Get a random wikipedia article",
    options = [
        interactions.Option(
            name="hide",
            description="When true, only you will see the response",
            type=interactions.OptionType.BOOLEAN,
            required=False,
        ),
    ],
)
async def randwiki(ctx, hide: bool = False):       
    a = wikipedia.random(pages=1)
    try:
        wikipedia.page(a, auto_suggest=False)
    except:
        a = wikipedia.search(a)[0]
    
    b = wikipedia.page(a, auto_suggest=False)
    embed = wiki2embed(b)
    await ctx.send(
        embeds=[embed],
        ephemeral=hide
    )
    return


### DATABASE COMMANDS ###

# DATA COMMAND #
@bot.command(
    name="database"
)
async def data(ctx):
    pass


# DATAGET COMMAND #
@data.subcommand(
    name="get",
)
@interactions.option(
    name="file",
    description="The database file to access",
    choices=[
        interactions.Choice(
            name="Rules Of The Internet",
            value="rules_of_the_internet.txt"
        )
    ],
    required=True,
)
@interactions.option(
    name="entry",
    description="The entry you wish to get",
    type=interactions.OptionType.STRING,
    required=False,
)
@interactions.option(
    name="hide",
    description="When true, only you will see the response",
    type=interactions.OptionType.BOOLEAN,
    required=False,
)
async def dateget(ctx: interactions.CommandContext, file: str, entry: str, hide: bool = False):
    names = {
        "rules_of_the_internet.txt": "Rules Of the Internet"
    }
    file = open("/database/" + file, "r")
    entries = file.read().split("===")
    enval = None
    i = 0
    while i < len(entries):
        if entries[i] == entry:
            enval = entries[i+1]
            break
        i = i + 2
    
    if enval is None:
        await ctx.send(
            content="Couldn't find `{0}` in `{1}`".format(entry.replace("`", "\\`"), file),
            ephemeral=True
        )
        return

    embed = interactions.Embed(
        title="",
        fields=[
            interactions.EmbedField(
                name="{0}, Entry: {1}".format(names[file], entry),
                value=str(enval)
            )
        ],
        ephemeral=hide
    )
        
    

    
### MISC COMMANDS ###

# CONFESSION COMMAND #
@bot.command(
    name="confess",
    description="Anonymously confess your deepest darkest secrets",
    options = [
        interactions.Option(
            name="confession",
            description="The confession you wish to make",
            type=interactions.OptionType.STRING,
            required=True,
        ),
    ],
)
async def super_cool_confession_command(ctx: interactions.CommandContext, confession: str):
    channel = await ctx.get_channel()
    
    embed = interactions.Embed(
        title="",
        fields=[
            interactions.EmbedField(
                name="Anonymous Confession",
                value=str(confession)
            )
        ],
    )
    
    await channel.send(embeds=[embed])
    await ctx.send(content="Done", ephemeral=True)

### START ###
@bot.event
async def on_ready():
    await interval(loop, 1)


### LOOPS ###
async def loop():
    global second
    
    await bot.change_presence(
        interactions.ClientPresence(
            afk=False,
            status=interactions.StatusType.IDLE,
            since=benus,
            activities=[
                interactions.PresenceActivity(
                    name="curious minds",
                    type=interactions.PresenceActivityType.LISTENING,
                )
            ]
        )
    )
    
    print(second)
    second = second + 1


benus = time.time()
keep_alive()
bot.start()
```
(apologies for the weird variable names)
here's the other python scripts I have
`keep_alive.py`:
```py
from flask import Flask
from threading import Thread
import random


app = Flask('')

@app.route('/')
def home():
	return 'I like men'

def run():
  app.run(
		host='0.0.0.0',
		port=random.randint(2000,9000)
	)

def keep_alive():
	'''
	Creates and starts new thread that runs the function run.
	'''
	t = Thread(target=run)
	t.start()
```
`shortcuts.py`:
```py
import os
import wikipedia
import interactions
from discord.ext.commands import has_permissions, MissingPermissions
from keep_alive import keep_alive
import json
from threading import Thread
from time import sleep
import asyncio
from contextlib import suppress


async def interval(callback, interval):
    async def loop(callback, interval):
        while True:
            await callback()
            await asyncio.sleep(1)
        
    a = Thread(
        target=lambda : asyncio.run(loop(callback, interval))
    )
    a.start()

def wiki2embed(page):
    title = page.title
    desc = page.summary
    url = page.url
    if len(page.images) > 0:
        imgs = page.images
        image_url = ""
        for i in imgs:
            if i.endswith(".png") or i.endswith(".jpg") or i.endswith(".jpeg"):
                image_url = i
                break
    else:
        image_url = ""
    embed = interactions.Embed(
        title=title,
        description=desc,
        image=interactions.EmbedImageStruct(
            url=image_url,
            height=300,
            width=300,
        ),
        url=url,
    )
    return embed
```

### List the steps.

I was simply programming my bot I don't know how I exactly encountered this error

### What you expected.

I expected it to not give me this error

### What you saw.

Instead, I received this error given from my Python terminal:
```
Traceback (most recent call last):
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/interactions/api/http/request.py", line 152, in request
    data = await response.json(content_type=None)
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    bot = interactions.Client(token=token)
  File "/home/runner/hall-of-information/venv/lib/python3.8/site-packages/interactions/client/bot.py", line 115, in __init__
    self.me = Application(**data, _client=self._http)
TypeError: type object argument after ** must be a mapping, not NoneType
```

### What version of the library did you use?

stable

### Version specification

Python 3.8.12

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
This is an issue with replit. Typing `kill 1` into the console usually fixed the issue

**Comment by LuantistDork** [comment]
I tried typing `kill 1` and it didn't seem to work

**Comment by sillyElvy** [comment]
> I tried typing `kill 1` and it didn't seem to work

There's nothing we can really do so I guess just try to run that command until it works?

**Comment by LuantistDork** [comment]
alright

**Comment by LuantistDork** [comment]
worked, thanks
