### ISSUE TITLE
Issue when trying to integrate into an existing bot

### ISSUE THREAD

**Issue by TomMaud** [interactions-py/interactions.py#110]
I've got it working on a brand new bot but when adding to an existing bot I get this error
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from discord_slash import SlashCommand
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/__init__.py", line 11, in <module>
    from .client import SlashCommand
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/client.py", line 11, in <module>
    from . import context
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/context.py", line 11, in <module>
    class SlashContext:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/context.py", line 120, in SlashContext
    allowed_mentions: discord.AllowedMentions = None,
AttributeError: module 'discord' has no attribute 'AllowedMentions'

**Comment by ghost** [comment]
not problem with your bot. also, if you are asking this, i think you need to learn how to read tracebacks.
I think problem is in how you importing discord.py. Can you show your imports part?

**Comment by eunwoo1104** [comment]
Duplicate of #35
