### ISSUE TITLE
[BUG] AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by BaranKazan** [interactions-py/interactions.py#1285]
### AttributeError: 'str' object has no attribute 'get'

Hey everyone. When I'am trying to run this code:

```
import interactions

bot = interactions.Client(token="your_secret_bot_token")

bot.start()
```

I'am getting this error:
```
Could not prepare the client:
Traceback (most recent call last):
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\client\bot.py", line 352, in _ready
    await self.__sync()
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\client\bot.py", line 429, in __sync
    _guilds = await self._http.get_self_guilds()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\api\http\guild.py", line 30, in get_self_guilds
    if guild.get("id"):
       ^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000248E6B2D590>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000248E6B4FAF0>, 180937.593)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000248E6B2E690>
```

I don't know what I'am doing wrong. I tried using different computer but I'am still getting same error. I'm running on Python11 but I also tried Python9 but still the same issue.

### List the steps.

1. Installing Python11
2. Running: `pip install discord-py-slash-command` in terminal
3. Running this code: 
```
import interactions

bot = interactions.Client(token="your_secret_bot_token")

bot.start()
```

### What you expected.

Running application I guess xD

### What you saw.

C:\Users\baran\Documents\Git\Rank-Bot\venv\Scripts\python.exe C:\Users\baran\Documents\Git\Rank-Bot\main.py 
Could not prepare the client:
Traceback (most recent call last):
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\client\bot.py", line 352, in _ready
    await self.__sync()
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\client\bot.py", line 429, in __sync
    _guilds = await self._http.get_self_guilds()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\Documents\Git\Rank-Bot\venv\Lib\site-packages\interactions\api\http\guild.py", line 30, in get_self_guilds
    if guild.get("id"):
       ^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000248E6B2D590>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000248E6B4FAF0>, 180937.593)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000248E6B2E690>

Process finished with exit code -1073741819 (0xC0000005)

### What version of the library did you use?

stable

### Version specification

4.2.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Toricane** [comment]
Did you replace `"your_secret_bot_token"` with your bot's token?

**Comment by BaranKazan** [comment]
Yeah, I even had Guild ID value in default and it still didn't work. I couldn't be the only one having this issue, or am I?

**Comment by Damego** [comment]
I see you have outdated version. Please, update it up to v4.4.0

**Comment by BaranKazan** [comment]
There is no v4.4.0 that is available in pypi.

[https://pypi.org/project/discord-py-slash-command/#history](url)

**Comment by AstreaTSS** [comment]
Hey - that PyPI package is no longer active. The library now uses `discord-py-interactions`, which has 4.4.0.

**Comment by BaranKazan** [comment]
Just installed it from the Git Repository. It worked, but getting a different error message.

`'401: Unauthorized'. Make sure that your token is set properly.`

I added the client secret token but I'am still getting this issue. I can investigate myself what the problem is, but Thanks for the help!

**Comment by BaranKazan** [comment]
Cant find any solutions. I have tried kicking out the bot and invited back to the server but it didnt work. This is the full error message I'm getting:
```
'401: Unauthorized'. Make sure that your token is set properly.
Traceback (most recent call last):
  File "/Users/barankazan/PycharmProjects/Rank-Bot/main.py", line 6, in <module>
    bot.start()
  File "/Users/barankazan/PycharmProjects/Rank-Bot/venv/lib/python3.11/site-packages/interactions/client/bot.py", line 203, in start
    raise e from e
  File "/Users/barankazan/PycharmProjects/Rank-Bot/venv/lib/python3.11/site-packages/interactions/client/bot.py", line 200, in start
    self._loop.run_until_complete(self._ready(token=token))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/barankazan/PycharmProjects/Rank-Bot/venv/lib/python3.11/site-packages/interactions/client/bot.py", line 436, in _ready
    data = await self._http.get_current_bot_information()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barankazan/PycharmProjects/Rank-Bot/venv/lib/python3.11/site-packages/interactions/api/http/client.py", line 116, in get_current_bot_information
    return await self._req.request(Route("GET", "/oauth2/applications/@me"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barankazan/PycharmProjects/Rank-Bot/venv/lib/python3.11/site-packages/interactions/api/http/request.py", line 188, in request
    raise LibraryException(
interactions.api.error.LibraryException: 
  Error 0 | Unknown error:
  '401: Unauthorized'. Make sure that your token is set properly.
  Severity 50.
```
I have generated token multiple times so there is no issue on that part.

**Comment by Damego** [comment]
How did you put the bot token? Directly or via `getenv`?

**Comment by Wolfhound905** [comment]
> I added the client secret token 

You need your bot token.
![image](https://user-images.githubusercontent.com/58155937/220685006-a49b15b4-4bce-48ca-82e6-4ce13c083be1.png)

**Comment by BaranKazan** [comment]
You have no idea how stupid I'm feeling right now. Thank you all for the help, application is working.
