### ISSUE TITLE
[BUG] RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.

### ISSUE THREAD

**Issue by baileyqdotme** [interactions-py/interactions.py#1387]
### Library Version

5.2.0

### Describe the Bug

When I run my discord bot I get an error (see it in traceback)!

My code is below:

```python
G:\Projects\Python\Discord.py\ssmp discord bot>python main.py
C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\attr\_make.py:918: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Class `Intents` received an invalid and unexpected value `<Intents value=32767>`, a new enum item will be created to represent this value. Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues
GUILD intent has not been enabled; this is very likely to cause errors
Traceback (most recent call last):
  File "G:\Projects\Python\Discord.py\ssmp discord bot\main.py", line 15, in <module>
    bot.start(settings.TOKEN)
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 951, in start
    asyncio.run(self.astart(token))
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 907, in astart
    await self.login(token)
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 890, in login
    self._user = ClientUser.from_dict(me, self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\discord\base.py", line 36, in from_dict
    data = cls._process_dict(data, client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\discord\user.py", line 163, in _process_dict
    data = super()._process_dict(data, client)
           ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021DA2BC1AD0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000021DA2B7E7B0>, 5370.281)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000021DA2BC1910>
```

### Steps to Reproduce

[1] Install the version of interactions provided and install python 3.11.2
[2] Use the code provided above in "Describe the bug" 
[3] Fill in your token and watch.

### Expected Results

I expected the bot to run.

### Traceback

G:\Projects\Python\Discord.py\ssmp discord bot>python main.py
C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\attr\_make.py:918: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Class `Intents` received an invalid and unexpected value `<Intents value=32767>`, a new enum item will be created to represent this value. Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues
GUILD intent has not been enabled; this is very likely to cause errors
Traceback (most recent call last):
  File "G:\Projects\Python\Discord.py\ssmp discord bot\main.py", line 15, in <module>
    bot.start(settings.TOKEN)
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 951, in start
    asyncio.run(self.astart(token))
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 907, in astart
    await self.login(token)
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 890, in login
    self._user = ClientUser.from_dict(me, self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\discord\base.py", line 36, in from_dict
    data = cls._process_dict(data, client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baile\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\discord\user.py", line 163, in _process_dict
    data = super()._process_dict(data, client)
           ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021DA2BC1AD0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000021DA2B7E7B0>, 5370.281)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000021DA2BC1910>

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
Hello - this error usually happens because you have an outdated version of attrs. Please confirm you have the latest version by using `pip install -U attrs`.

**Comment by baileyqdotme** [comment]
> Hello - this error usually happens because you have an outdated version of attrs. Please confirm you have the latest version by using `pip install -U attrs`.

All working now,
Thanks!
