### ISSUE TITLE
[BUG] fetch_guild() method not working.

### ISSUE THREAD

**Issue by Suterusu1337** [interactions-py/interactions.py#1393]
### Library Version

5.2.0

### Describe the Bug

When calling Client.fetch_guild(_id_, force=True) the traceback reports:

`Traceback (most recent call last):
  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/client/client.py", line 1810, in __dispatch_interaction
    response = await callback

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/client/client.py", line 1693, in _run_slash_command
    return await command(ctx, **ctx.kwargs)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/models/internal/command.py", line 132, in __call__
    await self.call_callback(self.callback, context)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/models/internal/application_commands.py", line 770, in call_callback
    return await self.call_with_binding(callback, ctx)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/models/internal/callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)

  File "/home/ubuntu/discord/bot.py", line 148, in debug
    guild = await bot.fetch_guild(1234, force=True)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/client/client.py", line 2021, in fetch_guild
    return await self.cache.fetch_guild(guild_id, force=force)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/client/smart_cache.py", line 594, in fetch_guild
    data = await self._client.http.get_guild(guild_id)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/api/http/http_requests/guild.py", line 58, in get_guild
    result = await self.request(Route("GET", "/guilds/{guild_id}"), params=params)

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/api/http/http_client.py", line 387, in request
    async with self.__session.request(route.method, route.url, **kwargs) as response:

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/api/http/route.py", line 90, in url
    return f"{self.BASE}{self.resolved_path}"

  File "/home/ubuntu/discord/bot-venv/lib/python3.10/site-packages/interactions/api/http/route.py", line 71, in resolved_path
    return self.path.format_map({k: _uriquote(v) if isinstance(v, str) else v for k, v in self.params.items()})

KeyError: 'guild_id'
`

### Steps to Reproduce

Use the method as documented.

### Expected Results

A guild object returned from the API.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
This is replicable. A strange error too - we'll look into it.

**Comment by AstreaTSS** [comment]
Fixed as of [7bf8a9f](https://github.com/interactions-py/interactions.py/commit/7bf8a9f906de869cbeb3a720a9067d3e46b76097).
