### ISSUE TITLE
A strange mistake.

### ISSUE THREAD

**Issue by Nezernite** [interactions-py/interactions.py#171]
```
Detected discord.Client! It is highly recommended to use `commands.Bot`. Do not add any `on_socket_response` event.
run
```
In a few seconds
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord_slash\client.py:294> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord_slash\client.py", line 312, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id = scope)
  File "C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```
please help me.
code:
```
import discord
from discord_slash import SlashCommand
from config2 import token

client = discord.Client(intents=discord.Intents.all())
slash = SlashCommand(client, sync_commands=True)

guild_ids = [767088657986617385]


class MyClient(discord.Client):
    @client.event
    async def on_ready():
        print("run")

    @slash.slash(name="ping", guild_ids=guild_ids)
    async def _ping(ctx): # Defines a new "context" (ctx) command called "ping."
        await ctx.send(f"Pong! ({client.latency*1000}ms)")



client.run(token)
```

**Comment by ghost** [comment]
strange code. why you put all in class? i think you need to read docs for d.py. also use commands.Bog from discord.ext. more in discord.py docs

**Comment by LordOfPolls** [comment]
This looks like the bot doesn't have the application commands scope

**Comment by Nezernite** [comment]
> странный код. зачем ты всех ставишь в класс? Я думаю, вам нужно прочитать документацию по d.py. также используйте command.Bog из discord.ext. подробнее в документах discord.py

Understand. I will fix
