### ISSUE TITLE
Getting AttributeError on registering slash commands

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#183]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from discord_slash.utils.manage_commands import create_option
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/__init__.py", line 11, in <module>
    from .client import SlashCommand
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/client.py", line 11, in <module>
    from . import context
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/context.py", line 13, in <module>
    class SlashContext:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/context.py", line 131, in SlashContext
    allowed_mentions: discord.AllowedMentions = None,
AttributeError: module 'discord' has no attribute 'AllowedMentions'

**Comment by quirky-bluejay** [comment]
Can you give your d.py version and the version of this lib, thanks

**Comment by ghost** [comment]
discord.py --> 1.7.2
discord-py-slash-command --> 1.1.2
