### ISSUE TITLE
`SlashCommand.to_dict()` raises KeyError if guild/global mixed subcommand exists

### ISSUE THREAD

**Issue by eunwoo1104** [interactions-py/interactions.py#184]
```py
@slash.subcommand(base="group", subcommand_group="user", name="ban",
                  description="Bans the user.",
                  subcommand_group_description="Everything about user.",
                  options=[manage_commands.create_option("user", "User to ban", 6, False)])
async def _group_user_ban(ctx: SlashContext, user=None):
    ...


@slash.subcommand(base="group", subcommand_group="user", name="kick",
                  description="Kicks the user.",
                  subcommand_group_description="Everything about user.",
                  guild_ids=[696562545489870858],
                  options=[manage_commands.create_option("user", "User to kick", 6, False)])
async def _group_user_kick(ctx: SlashContext, user=None):
    ...


@slash.subcommand(base="group", name="say", guild_ids=[696562545489870858],
                  description="Say something.", options=[manage_commands.create_option("text", "Any text.", 3, False)])
async def _group_say(ctx, text=None):
    ...
```
`/group user ban` is a global command, while other `/group ...` commands are guild commands.
This raises KeyError:
```py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\sions\PycharmProjects\discord-py-slash-command\discord_slash\client.py:308> exception=KeyError('group')>
Traceback (most recent call last):
  File "C:\Users\sions\PycharmProjects\discord-py-slash-command\discord_slash\client.py", line 322, in sync_all_commands
    cmds = await self.to_dict()
  File "C:\Users\sions\PycharmProjects\discord-py-slash-command\discord_slash\client.py", line 298, in to_dict
    wait[i][x]["options"].append(queue[i])
KeyError: 'group'
```
Note that this code works in 1.0.8.5, but not the later releases. Also, this won't happen if only guilds are mixed. (e.g. `/group user ban` is guild command of guild `658622641086660610`)

**Comment by i0bs** [comment]
For the sake of it, is this *still* a bug?

**Comment by LordOfPolls** [comment]
Yes. To resolve it, it requires the majority of command storage/retrieval to be overhauled.

Worth noting this affects a small minority of bots; the ones that allow custom commands, or tags. As per eun, is also only an issue if guild/global is mixed, not an issue if multiple guilds are mixed

**Comment by i0bs** [comment]
Should this be kept note of then past the 3.0.0 build?

**Comment by i0bs** [comment]
Will be fixed in v4.
