### ISSUE TITLE
SlashMessage.edit() raises HTTPException with "embeds" argument

### ISSUE THREAD

**Issue by Shmookoff** [interactions-py/interactions.py#185]
`SlashMessage.edit(embeds=[embed1, embed2])`
```py
Traceback (most recent call last):
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord_slash\client.py", line 744, in invoke_command
    await coro
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord_slash\model.py", line 253, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\app\cogs\subs.py", line 117, in sub_add
    await ctx.msg.edit(content='React with\n\t:one: for **first** wall,\n\t❌ for cancel,\n\t:two: for **second
** wall.', embeds=[group_embed, user_embed])
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord_slash\model.py", line 343, in edit
    await super().edit(**fields)
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord\message.py", line 1111, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord\http.py", line 156, 
in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "C:\Users\shmoo\Documents\Projects\GitHub\posthound\venv\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "C:\Users\shmoo\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps       
    return cls(
  File "C:\Users\shmoo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode       
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\shmoo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode   
    return _iterencode(o, 0)
  File "C:\Users\shmoo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default      
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Embed is not JSON serializable
```
While if i `SlashMessage.edit(embed=embed1)`, there isn't any errors

**Comment by hrmorley34** [comment]
Duplicate of #173?

**Comment by DarkAutumn2618** [comment]
> Duplicate of #173?

I believe so, I think it was the same error that I (the person who made #173) got when trying to do that as well
