### ISSUE TITLE
KeyError in _structured_raw_data everytime a slash command being used

### ISSUE THREAD

**Issue by Unluck-Y** [interactions-py/interactions.py#193]
Everytime someone uses a slash command, I get this error message (but everything is working fine):
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\unluc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\unluc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord_components\client.py", line 80, in on_socket_response
    ctx = self._get_context(res)
  File "C:\Users\unluc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord_components\client.py", line 342, in _get_context
    data = self._structured_raw_data(json)
  File "C:\Users\unluc\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord_components\client.py", line 310, in _structured_raw_data
    if "components" not in raw_data["message"]:
KeyError: 'message'

**Comment by LordOfPolls** [comment]
Can I see some example code of one of your commands that cause this

Please use code blocks

**Comment by Unluck-Y** [comment]
Sure:
```python
    @cog_ext.cog_slash(name = "qr", description = "Szöveg átalakítása QR kóddá", options = [{"name": "szöveg", "description": "A szöveg amit QR kóddá akarsz alakítani", "type": 3, "required": True}])
    async def qr(self, ctx, text): await fun.qr(ctx, text)

**Comment by LordOfPolls** [comment]
Im gunna need more than that, that code wouldnt cause the issue

That traceback doesnt show anything to do with this library, only the d.py methods. Are you doing anything non-standard anywhere? Does the error occur with a simple ping command (ie `await ctx.send("ping")`). Is the code open on github?

**Comment by Unluck-Y** [comment]
I got this error even with this code:
```python
@slash.slash(name = "teszt", description = "teszt")
async def teszt2(ctx):
    await ctx.send("a")
```

**Comment by quirky-bluejay** [comment]
That isn't an issue with this library, that's an issue with the `discord_components` libary

**Comment by LordOfPolls** [comment]
Completely derped and thought `discord_components` was part of d.py. My bad. I should go drink some coffee

**Comment by Unluck-Y** [comment]
Ohh sorry, I'm an idiot, and I can't read...
