### ISSUE TITLE
Compatibility issue with discord.py-components module

### ISSUE THREAD

**Issue by FightMan01** [interactions-py/interactions.py#196]
When I use the `discord.py-components` and click a button I get an error.
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord_slash/client.py", line 720, in on_socket_response
    if to_use["data"]["name"] in self.commands:
KeyError: 'name'
```

**Comment by artem30801** [comment]
Download the latest 1.2.0 release, this issue should be fixed there

**Comment by quirky-bluejay** [comment]
duplicate of #190
