### ISSUE TITLE
Setting `content` to `None` or `""` results in an error for `ComponentContext.edit_origin`

### ISSUE THREAD

**Issue by AstreaTSS** [interactions-py/interactions.py#254]
```python

# select options from select tutorial, more or less
select = create_select(
    options=[
        create_select_option("Lab Coat", value="coat", emoji="🥼"),
        create_select_option("Test Tube", value="tube", emoji="🧪"),
        create_select_option("Petri Dish", value="dish", emoji="🧫"),
    ]
)

# any command will work here, even slash commands
@bot.command()
async def test(ctx: commands.Context):
    await ctx.send("test", components=[create_actionrow(select)])

@bot.event
async def on_component(ctx: ComponentContext):
    await ctx.edit_origin(content=None) # or "", same result either way
```
results in:
```python
Traceback (most recent call last):
  File "PATH_TO_PYTHON\lib\site-packages\discord\client.py", line 343, in _run_event        
    await coro(*args, **kwargs)
  File "PATH_TO_PROGRAM/main.py", line IN_PROGRAM, in on_component
    await ctx.edit_origin(content="")
  File "PATH_TO_PYTHON\lib\site-packages\discord_slash\context.py", line 465, in edit_origin
    _json = await self._http.edit(_resp, self._token, files=files)
  File "PATH_TO_PYTHON\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
```

Ideally, the code shouldn't error and instead effectively remove the content from the message. It doesn't seem to do that, however.

It might be a Discord error that's unsolvable on our end (and honestly the more I look into it the more it really seems to be this) - I'm not sure. But it might be worth looking at.

**Comment by Toricane** [comment]
It happened to me when sending the message without content (which was the original select example), and I got the same error, and I PRed the doc to add in that `"test"`, so I think its Discord

**Comment by AstreaTSS** [comment]
Closing this myself due to the fact that this is likely a Discord issue, not a library issue (also, this issue was kind of dead, anyways).
