### ISSUE TITLE
Slash command greyed out even though I have permission

### ISSUE THREAD

**Issue by zurgeg** [interactions-py/interactions.py#256]
I created a simple bot with this module, and I believe this is a bug.
I was working with this bot, everything working normally, when suddenly **my permission based commands were greyed out**. I can't pinpoint the exact change that caused the issue, but it happened when I added a command I think. I'm still in the process of debugging, but believe this is a bug. 
What I have tried:
- [x] Deleting the commands
- [x] Unloading the cog
- [x] Deleting all slash commands
- [x] Restarting the bot
- [x] Using a different bot

Let me know if I should try any new debugging steps

**Comment by benwoo1110** [comment]
Can you send the actual code of your command with permissions that you are setting on it?

**Comment by zurgeg** [comment]
> 
> 
> Can you send the actual code of your command with permissions that you are setting on it?

@benwoo1110 Sure! Although, just to elaborate, **any new permissions I added would cause the command to be greyed out**, so I'm pretty sure this is a bug.
If I take the example command for cogs:
```
    @cog_ext.cog_slash(name="test")
    async def _test(self, ctx: SlashContext):
        embed = Embed(title="Embed Test")
        await ctx.send(embed=embed)
```
and set the default permission to False:
```
    @cog_ext.cog_slash(default_permission=False, name="test")
    async def _test(self, ctx: SlashContext):
        embed = Embed(title="Embed Test")
        await ctx.send(embed=embed)
```
that greys out the command, which is expected, because I didn't allow anyone access. However, then, I add a permission:
```
    @cog_ext.cog_slash(default_permission=False, name="test")
    @slash.permission(guild_id=config.guild_id, permissions=[create_permission(bot.owner, SlashCommandPermissionType.USER, permission=True)])
    async def _test(self, ctx: SlashContext):
        embed = Embed(title="Embed Test")
        await ctx.send(embed=embed)
```
and it remains greyed out.

**Comment by benwoo1110** [comment]
It needs to be a user id. Not 100% familiar with d.py, I suspect you likely need to do `bot.owner.id`

**Comment by zurgeg** [comment]
> 
> 
> It needs to be a user id. Not 100% familiar with d.py, I suspect you likely need to do `bot.owner.id`

@benwoo1110 Right 😅 , I wasn't actually using that code in production/testing and was too lazy to look at my real code, in my real code, I was using bot.owner_id, which will get the bot's owners' ID, still doesn't work however. Even when I tested this code with proper modifications made, it remains greyed out

**Comment by FayeDel** [comment]
> ```
>     @cog_ext.cog_slash(default_permission=False, name="test")
>     @slash.permission(guild_id=config.guild_id, permissions=[create_permission(bot.owner, SlashCommandPermissionType.USER, permission=True)])
>     async def _test(self, ctx: SlashContext):
>         embed = Embed(title="Embed Test")
>         await ctx.send(embed=embed)
> ```
> 

Bot's not defined in decorators (I've double-checked on this with how you put your permissions on), hence why you still couldn't see the command. I suggest you should have a reference of the owner_id somewhere else (Your config's an option, but that's again only a suggestion)

**Comment by zurgeg** [comment]
> 
> 
> > ```
> >     @cog_ext.cog_slash(default_permission=False, name="test")
> >     @slash.permission(guild_id=config.guild_id, permissions=[create_permission(bot.owner, SlashCommandPermissionType.USER, permission=True)])
> >     async def _test(self, ctx: SlashContext):
> >         embed = Embed(title="Embed Test")
> >         await ctx.send(embed=embed)
> > ```
> 
> Bot's not defined in decorators (I've double-checked on this with how you put your permissions on), hence why you still couldn't see the command. I suggest you should have a reference of the owner_id somewhere else (Your config's an option, but that's again only a suggestion)

I imported the bot in the scope, and I don't see any errors in the logs (it's **greyed out, not invisible**) @DeltaXWizard

**Comment by LordOfPolls** [comment]
How did you `import` bot into the scope

**Comment by zurgeg** [comment]
> 
> 
> How did you `import` bot into the scope

```python
from app import bot
```
Unless you mean something else? Additionally, I tried hardcoding the ID, and it still didn't work. (Also, pretty sure this is a bug, it was working before, now it doesn't work at all, even once I switched to a new file, and new bot token)

**Comment by benwoo1110** [comment]
Permissions code didnt change in this lib since the addition of it really, so did you change anything on your side? Its possible that the cog isn't loaded properly or you didn't enabled sync_commands=True

**Comment by zurgeg** [comment]
> 
> 
> Permissions code didnt change in this lib since the addition of it really, so did you change anything on your side? Its possible that the cog isn't loaded properly or you didn't enabled sync_commands=True

Maybe, I tried changing cogs to a command that used to work, and I haven't changed anything on my side side, and I ensured sync_commands=True is on. Although I did use positional arguments and not keywords (ie `SlashCommand(bot, True, False, True)`)

**Comment by benwoo1110** [comment]
Maybe I know why, what version of this lib are you using?

Edit: latest is v2.3.1, update if you are not using the latest

**Comment by zurgeg** [comment]
> 
> 
> Maybe I know why, what version of this lib are you using?

`2.0.0`

**Comment by benwoo1110** [comment]
Yea please update and try again.

**Comment by zurgeg** [comment]
Alright, will try. Odd that it seemingly broke out of nowhere though, maybe add a sort of "troubleshooting" checklist to the issue template?

**Comment by benwoo1110** [comment]
Yea good idea to have an issue template that indicates to always try the latest release first among other things. Though I think updating is a very common knowledge....

It should work after you update bcu cogs didn't support permission decorator until this commit https://github.com/discord-py-slash-commands/discord-py-interactions/commit/e4c7db88e97420973ba72520633d39f9cb354bf7

**Comment by zurgeg** [comment]
@benwoo1110 
```
future: <Task finished coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord_slash\client.py:359> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn 4.permissions.0.id: This field is required')>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord_slash\client.py", line 465, in sync_all_commands
    await self.req.update_guild_commands_permissions(scope, new_perms)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 4.permissions.0.id: This field is required
```
Maybe an API update broke something?

**Comment by benwoo1110** [comment]
That means your id is None, likely due to what @DeltaXWizard mentioned about owner not being init yet.

**Comment by zurgeg** [comment]
Ahhhh, I wasn't aware that was what he meant

**Comment by zurgeg** [comment]
Yep, permissions are okay now, thanks!
