### ISSUE TITLE
You are not authorized to perform this action on this application

### ISSUE THREAD

**Issue by PythonCoderAS** [interactions-py/interactions.py#259]
I tried adding in the slash command client for the first time to my existing bot (without any slash commands) and I got this bizarre exception (home path replaced with `~`):

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at ~/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord_slash/client.py:359> exception=Forbidden('403 Forbidden (error code: 20012): You are not authorized to perform this action on this application')>
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord_slash/client.py", line 382, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "~/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 20012): You are not authorized to perform this action on this application
```

I have no clue what I did to trigger this error, since I have never used slash commands before.

**Comment by PythonCoderAS** [comment]
It seems that I was giving an application ID that did not match the current client user's ID, my mistake.
