### ISSUE TITLE
"Missing Access" error when enabling the bot

### ISSUE THREAD

**Issue by itsSourCream** [interactions-py/interactions.py#277]
If you use  `slash = Slash Command(client, sync_commands=True)`, then when enabled, the bot will give an error - 
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\savel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\client.py:359> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\savel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\client.py", line 382, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "C:\Users\savel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

The error does not affect the operation of the bot.

**Comment by itsSourCream** [comment]
I solved it. It turns out that when the bot is kicked from the server, it cannot load slash commands there, which is why an error appears.
