### ISSUE TITLE
Cannot send file: _request() got an unexpected keyword argument 'form'

### ISSUE THREAD

**Issue by reteps** [interactions-py/interactions.py#279]
Code:

```py
        fname = f"{challenge.category.name}_{challenge.name}_log.txt"
        with open(fname, 'w') as fw:
             fw.write("File contents")
        await ctx.channel.send(file=discord.File(fname))
```

Also tried:

+ `ctx.send`
+ `ctx.send(file=BYTES_OF_FILE)`

Full traceback:

```
Traceback (most recent call last):
  File "/home/retep/.local/lib/python3.8/site-packages/discord_slash/client.py", line 1208, in invoke_command
    await func.invoke(ctx, **args)
  File "/home/retep/.local/lib/python3.8/site-packages/discord_slash/model.py", line 209, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "/mnt/c/Users/Peter/repos/pwnybot/lib/util.py", line 75, in wrapper
    await func(self, ctx, *args, **kwargs)
  File "/mnt/c/Users/Peter/repos/pwnybot/cogs/chal/chal.py", line 97, in archive
    await ctx.channel.send(file=discord.File(fname))
  File "/home/retep/.local/lib/python3.8/site-packages/discord_slash/dpy_overrides.py", line 323, in send_override
    return await send(channel, *args, **kwargs)
  File "/home/retep/.local/lib/python3.8/site-packages/discord_slash/dpy_overrides.py", line 264, in send
    data = await state.http.send_files(
  File "/home/retep/.local/lib/python3.8/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/retep/.local/lib/python3.8/site-packages/aiohttp/client.py", line 321, in request
    return _RequestContextManager(self._request(method, url, **kwargs))
TypeError: _request() got an unexpected keyword argument 'form'
```

**Comment by reteps** [comment]
Never mind, had an outdated `discord.py` version.
