### ISSUE TITLE
[BUG] StopIteration raised in trivial use of add_slash_command()

### ISSUE THREAD

**Issue by lexicalunit** [interactions-py/interactions.py#327]
**Describe the bug**
Just to get started I'm converting some code I have that uses `discord.py` over to use slash commands. I am not using the `discord.py` commands so I hope that this won't be too challenging. This is basically what my code looks like:
```python
class MyBot(discord.Client):
    def __init__(self, [...]):
        self.slash = SlashCommand(self, sync_commands=True)

        [...]

        async def hello_world():
            print("hello world")

        self.slash.add_slash_command(hello_world, "hello", "prints hello world")

    [...]
```

**Reproducing steps**
Given the above class, execute the following:
```
client = MyBot([...])
client.run()
```

**What's normally expected**
I would expect the bot to start as normal and handle the `/hello` slash command in addition to all the other functionality within the bot.

**What actually happened**
I get this output:
```
[...]
[2021-09-04 10:22:43][discord_slash][WARNING] - Detected discord.Client! It is highly recommended to use `commands.Bot`. Do not add any `on_socket_response` event.
[...]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/hupper/ipc.py", line 319, in spawn_main
    func(**kwargs)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/hupper/worker.py", line 252, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/me/source/mybot/src/mybot/__init__.py", line 3864, in main
    client = MyBot(
  File "/Users/me/source/mybot/src/mybot/__init__.py", line 483, in __init__
    self.slash.add_slash_command(hello_world, "hello", "prints hello world")
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/discord_slash/client.py", line 631, in add_slash_command
    options = manage_commands.generate_options(cmd, description, connector)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/mybot-IQfhdu4x-py3.8/lib/python3.8/site-packages/discord_slash/utils/manage_commands.py", line 293, in generate_options
    if next(params).name in ("self", "cls"):
StopIteration
```

**Versions**
- [x] I am using `discord.py` rev `45d498c1b76deaf3b394d17ccf56112fa691d160`, the last commit.
- [x] I am not using `discord-py-interactions = "^3.0.2"`

**Comment by Catalyst4222** [comment]
The reason why it fails is because it expects at least one parameter, which would be `ctx`. If you added a slash command with the decorator, and the function had no parameters, it would also fail

**Comment by lexicalunit** [comment]
That fixed it! Thanks! I hope you don't mind, I may be opening a few issues as I work through this.

**Comment by Toricane** [comment]
> That fixed it! Thanks! I hope you don't mind, I may be opening a few issues as I work through this.

Instead of making issues for your problems, please consider joining our Discord server and asking your question in #support. There are a lot of helpers who can help you there!
