### ISSUE TITLE
Why an I getting this error

### ISSUE THREAD

**Issue by IgnacyFluder** [interactions-py/interactions.py#35]
Traceback (most recent call last):
  File "C:\Users\ignac\OneDrive\Pulpit\BOT\botRewrite.py", line 9, in <module>
    from discord_slash import SlashCommand
  File "C:\Users\ignac\AppData\Roaming\Python\Python38\site-packages\discord_slash\__init__.py", line 11, in <module>
    from .client import SlashCommand
  File "C:\Users\ignac\AppData\Roaming\Python\Python38\site-packages\discord_slash\client.py", line 6, in <module>
    from . import model
  File "C:\Users\ignac\AppData\Roaming\Python\Python38\site-packages\discord_slash\model.py", line 8, in <module>
    class SlashContext:
  File "C:\Users\ignac\AppData\Roaming\Python\Python38\site-packages\discord_slash\model.py", line 64, in SlashContext
    allowed_mentions: discord.AllowedMentions = None,
AttributeError: module 'discord' has no attribute 'AllowedMentions'

**Comment by eunwoo1104** [comment]
Which discord.py version are you using?

**Comment by IgnacyFluder** [comment]
1.5.1

**Comment by eunwoo1104** [comment]
Hmm... That's weird then. The only thing I can say is reinstalling discord.py

**Comment by IgnacyFluder** [comment]
That worked lol

**Comment by eunwoo1104** [comment]
oof
