### ISSUE TITLE
cog_ext.cog_slash unable to register for specific guild. [BUG] 

### ISSUE THREAD

**Issue by TheORC** [interactions-py/interactions.py#372]
**Describe the bug**
Not sure if this is a bug or not, but there seams to be an issue when supplying the `guild_ids=[...]` attribute when creating a `cog_ext.cog_slash` command.  When I do this, the cog commands are not registered and an error produced.

**Reproducing steps**
Create a cog to register a simple command.  For instance the default example code.

```from discord import Embed

from discord.ext import commands
from discord_slash import cog_ext, SlashContext

from discord_slash.utils.manage_commands import create_option, create_choice


class BotEvents(commands.Cog):

    def __init__(self, bot):
        """Initialize important information."""
        self.bot = bot

    @cog_ext.cog_slash(
        name="test",
        description="This is just a test command, nothing more.",
        guild_ids=[***],
        options=[
           create_option(
               name="optone",
               description="This is the first option we have.",
               option_type=3,
               required=True,
               choices=[
                   create_choice(
                       name="ChoiceOne",
                       value="DOGE!"
                       ),
                   create_choice(
                       name="ChoiceTwo",
                       value="NO DOGE"
                       )
                   ]
               )
           ])
    async def _test(self, ctx: SlashContext, optone: str):
        embed = Embed(title="Embed Test")
        await ctx.send(embed=embed)


def setup(bot):
    bot.add_cog(BotEvents(bot))
```

Replace `***` with a guild id. 
Run the code.

**What's normally expected**
I expect the cog command to be registered and usable on Discord.

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py:415> exception=IncorrectCommandData('Options are required for subcommands / subcommand groups')>
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py", line 444, in sync_all_commands
    existing_by_name[cmd["name"]] = model.CommandData(**cmd)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\model.py", line 102, in __init__
    self.options.append(OptionData(**option))
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\model.py", line 62, in __init__
    raise error.IncorrectCommandData(
discord_slash.error.IncorrectCommandData: Options are required for subcommands / subcommand groups
```

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
Closing in favor of #288 .
