### ISSUE TITLE
[BUG] Context menus cause a `TypeError` from `InteractionResolvedData`

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#406]
**Describe the bug**
`TypeError` in `InteractionResolvedData` crashes the bot when using a user context menu.
Error: `TypeError: interactions.api.models.user.User() argument after ** must be a mapping, not User`
There are more of these similar errors, in `InteractionResolvedData`, `interactions/models/misc.py` lines 36-56
This specific error appears since it is the first of many.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

0. Use the `dev` branch
1. Make a context menu:
```py
@bot.command(
    type=interactions.ApplicationCommandType.USER,
    name="user menu",
    scope=874781880489222154,
)
async def user_menu(ctx: interactions.CommandContext):
    await ctx.send("hi")
```
2. Run the bot
3. Use the user context menu

**What's normally expected**
When I use the user context menu, the command should run without any errors.

**What actually happened**
The command does run, but right after it sends, "hi," it errors with the traceback provided below, and ultimately shows `ERROR:gateway:(ln.65):The client was unable to send a heartbeat, closing the connection.`

```py
Traceback (most recent call last):
  File "c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\main.py", line 263, in <module>
    bot.start()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 116, in start
    self.loop.run_until_complete(self.ready())
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 155, in ready
    await self.login(self.token)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 112, in login
    await self.websocket.connect(token, self.shard, self.presence)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 174, in connect
    await self.handle_connection(stream, shard, presence)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 237, in handle_connection
    self.handle_dispatch(event, data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\ext\wait_for\wait_for.py", line 55, in handle_dispatch
    context = self.contextualize(data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 375, in contextualize
    return context(**data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 115, in __init__
    self.data = InteractionData(**self.data) if self._json.get("data") else None
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\misc.py", line 108, in __init__
    InteractionResolvedData(**self.resolved) if self._json.get("resolved") else None
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\misc.py", line 35, in __init__
    [
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\misc.py", line 36, in <listcomp>
    self.users.update({user: User(**self.users[user])})
TypeError: interactions.api.models.user.User() argument after ** must be a mapping, not User
```
When I looked in the file where it raised the error, I found this snippet of code:
```py
        if self._json.get("users"):
            [
                self.users.update({user: User(**self.users[user])})
                for user in self._json.get("users")
            ]
        if self._json.get("members"):
            [
                self.members.update({member: Member(**self.members[member])})
                for member in self._json.get("members")
            ]
        if self._json.get("roles"):
            [
                self.roles.update({role: Role(**self.roles[role])})
                for role in self._json.get("roles")
            ]
        if self._json.get("channels"):
            [
                self.channels.update({channel: Channel(**self.channels[channel])})
                for channel in self._json.get("channels")
            ]
        if self._json.get("messages"):
            [
                self.messages.update({message: Message(**self.messages[message])})
                for message in self._json.get("messages")
            ]
```
These are the ones that cause this issue.
I propose that this code is modified to include a `._json`, like `Object(**self.objects[object]._json)`.

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
This is likely an issue to do with how `for foo in self.bar.get("foo")` messages is performed. `foo` is assumed as an object itself instead of the key which we want when performing the K:V transition for object generation, which `bar` does not hold since it represents a `dict` type.

**Comment by i0bs** [comment]
Working with this more closely, this is the proposed code I have put into `unstable` thus far that seems to eliminate errors like this:

```py
        self.attr = (
            Object(**attr)
            if not isinstance(attr, Object)
            else self._json.get("attr")
            # for sub_attr in self.attr  # this is if it's a loop/nested attr.
        )
```

This seems to work perfectly with our recursion in most situations and I have not yet found an edgecase for it.

**Comment by i0bs** [comment]
cc. @DeltaXWizard I believe this was fixed although not sure if we pushed the internal fix to a commit yet.

**Comment by FayeDel** [comment]
Most likely;
I'm not sure what commit fixes it, but I ran that exact example in the `unstable` branch and I haven't gotten any error, following the same reproduction steps.
