### ISSUE TITLE
[BUG] `TypeError` crashes the bot when using a message context menu

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#407]
**Describe the bug**
This is separate from #406 because it has a different error, in a different place.
When using a message context menu, I get `TypeError: argument of type 'NoneType' is not iterable`

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

0. Use `dev` branch
1. Create message context menu:
```py
@bot.command(
    type=interactions.ApplicationCommandType.MESSAGE,
    name="message menu",
    scope=874781880489222154,
)
async def message_menu(ctx: interactions.CommandContext):
    await ctx.send("hi")
```
2. Run the bot
3. The command fails, does not send the message, the error is in the console
4. After around a minute or less, the bot crashes and displays `ERROR:gateway:(ln.65):The client was unable to send a heartbeat, closing the connection.` in the console

**What's normally expected**
When I use the message context menu, it should execute and send "hi" without any errors.

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```py
Traceback (most recent call last):
  File "c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\main.py", line 271, in <module>
    bot.start()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 116, in start
    self.loop.run_until_complete(self.ready())
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in 
run_until_complete
    return future.result()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 155, in ready
    await self.login(self.token)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 112, in login
    await self.websocket.connect(token, self.shard, self.presence)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 174, in connect
    await self.handle_connection(stream, shard, presence)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 237, in handle_connection
    self.handle_dispatch(event, data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\ext\wait_for\wait_for.py", line 49, in handle_dispatch
    super().handle_dispatch(event, data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 310, in handle_dispatch
    context = self.contextualize(data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\gateway.py", line 375, in contextualize
    return context(**data)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 120, in __init__
    if str(self.data.target_id) in self.data.resolved.users:
TypeError: argument of type 'NoneType' is not iterable
```
Error is thrown in the `__init__` method of `CommandContext`, file directory `interactions/context.py` line 120

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
Flagging this internally as an issue to be addressed hopefully next release.

**Comment by i0bs** [comment]
Closing this in favor of #406
