### ISSUE TITLE
[BUG] Unable to send button with emoji

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#408]
**Describe the bug**
I am unable to send a button with an emoji.
I am fairly certain that I'm doing it right. If not, please mention the correct usage.
- I've also tried `Emoji(name="🟦")`, same error
My code is down below:

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

0. Use `dev` branch, have not tested on `stable`
1. Create command
2. Create component with the following code:
```py
primary_button = interactions.Button(
    style=interactions.ButtonStyle.PRIMARY,
    label="PRIMARY",
    emoji=interactions.Emoji(name="blue_square", require_colons=True),
    custom_id="primary",
)
```
3. Send the button: `await ctx.send("button:", components=primary_button)`
4. Command fails and error is in the console

**What's normally expected**
When I use the slash command, the button should be sent.

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```py
Traceback (most recent call last):
  File "c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\main.py", line 283, in component_command
    await ctx.send("button:", components=primary_button)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 272, in send
    await func()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 265, in func
    await self.client.create_interaction_response(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\http.py", line 2061, in create_interaction_response
    return await self._req.request(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\http.py", line 200, in request
    async with self.session.request(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps 
    return _default_encoder.encode(obj)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode 
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Emoji is not JSON serializable
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
Can you tell me what the terminal returns when you do this with the logger set to `DEBUG`?

Additionally, `id` must be present when using the `Emoji()` object.
