### ISSUE TITLE
[BUG] choices not working

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#409]
When using choices the following error still appears:
`AttributeError: 'dict' object has no attribute '_json'`

the following change seems to fix it:
(command.py ln. 116)
```py
if isinstance(self._json.get("choices"), dict):  # this errors because it is a list
```

to
```py
if all(isinstance(choice, dict) for choice in self.choices): 
```

**Comment by Toricane** [comment]
Reproducible by me, here's the full traceback:
```py
Traceback (most recent call last):
  File "c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\YouTube-tutorials\discord-py-interactions\ep1_simple_slash_commands\reference.py", line 105, in <module>
    async def hello_choices(ctx: interactions.CommandContext, choose_wisely):
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\client.py", line 358, in decorator
    commands: List[ApplicationCommand] = command(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\decor.py", 
line 83, in command
    payload: ApplicationCommand = ApplicationCommand(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\command.py", line 220, in __init__
    [Option(**option) for option in self.options] if self._json.get("options") else None
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\command.py", line 220, in <listcomp>
    [Option(**option) for option in self.options] if self._json.get("options") else None
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\command.py", line 119, in __init__
    self._json["choices"] = [choice._json for choice in self.choices]
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\models\command.py", line 119, in <listcomp>
    self._json["choices"] = [choice._json for choice in self.choices]
AttributeError: 'dict' object has no attribute '_json'
```

**Comment by i0bs** [comment]
Will be addressed in the next release, thanks for bringing it to our attention
