### ISSUE TITLE
[BUG] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by gibbiemonster** [interactions-py/interactions.py#464]
**Describe the bug**
Please give us an in-depth description of the bug you're having.

When trying to run a bot using async, there is an error detailing `TypeError: string indices must be integers` even when string indices aren't used in the program.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Use the code on the docs.
3. Run
4. See the traceback error given in the terminal or logger file.
^ this is EXACTLY how to reproduce. 

**What's normally expected**
The bot to run as expected.

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```
Traceback (most recent call last):
  File "/Users/myname/Desktop/Inspirobot/inspirobot.py", line 26, in <module>
    async def generate(ctx):
  File "/usr/local/lib/python3.9/site-packages/interactions/client.py", line 372, in decorator
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "/usr/local/lib/python3.9/site-packages/interactions/client.py", line 372, in <listcomp>
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/interactions/client.py", line 218, in _synchronize
    names: List[str] = [command["name"] for command in commands] if commands else []
  File "/usr/local/lib/python3.9/site-packages/interactions/client.py", line 218, in <listcomp>
    names: List[str] = [command["name"] for command in commands] if commands else []
TypeError: string indices must be integers
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Extra**

Code: 
```
# Register a new command
@bot.command(
    # We'll call it generate
    name="generate",
    # Set our description
    description="Generate a new quote",
    # Scope
    scope=2751581248
)
async def generate(ctx):
    await ctx.send("Hello world!")
```

**Comment by FayeDel** [comment]
Hiya and thanks for making an issue!

This seems to be reproducible only if you have the wrong scope (aka guild id) provided. I've tested this with an invalid and valid scope, and it works only when you give it the correct guild ID. If not, it gives that error and returns a 50001 Missing Access.

**Comment by gibbiemonster** [comment]
Awesome!

So - I also found out that discord sometimes doesn't give you the full server ID, so try and use an alternative source for your ID's I guess.

**Comment by CheezusChrust** [comment]
I am having this same issue, and I am 100% positive I'm using the full server ID.

Error:
```
Traceback (most recent call last):
  File "C:\Users\Matthew\source\repos\PythonApplication2\PythonApplication2\PythonApplication2.py", line 10, in <module>
    async def fart(ctx: interactions.CommandContext):
  File "C:\Users\Matthew\Documents\Visual Studio Projects\Backup\env\lib\site-packages\interactions\client.py", line 372, in decorator
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "C:\Users\Matthew\Documents\Visual Studio Projects\Backup\env\lib\site-packages\interactions\client.py", line 372, in <listcomp>
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Matthew\Documents\Visual Studio Projects\Backup\env\lib\site-packages\interactions\client.py", line 218, in _synchronize
    names: List[str] = [command["name"] for command in commands] if commands else []
  File "C:\Users\Matthew\Documents\Visual Studio Projects\Backup\env\lib\site-packages\interactions\client.py", line 218, in <listcomp>
    names: List[str] = [command["name"] for command in commands] if commands else []
TypeError: string indices must be integers
```

Full code:

```python
import interactions

bot = interactions.Client(token="TOKENHERE")

@bot.command(
    name="testcommand",
    description="This is a cool epic description",
    scope=546858965552594944
)
async def testcommand(ctx: interactions.CommandContext):
    await ctx.send("testing")

bot.start()
```

I am also using this library standalone.

**Comment by i0bs** [comment]
I'd recommend joining our [support server](https://discord.gg/interactions) and sending something in one of our library channels. If you're on PyPI release/stable branch please use `#stable`, otherwise refer to `#unstable`.
