### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by rowisahub** [interactions-py/interactions.py#5]
It says it can't get the privileged intents 

```
Traceback (most recent call last):
  File "R:\row\slash_command\slash.py", line 16, in <module>
    bot.run("THE REAL TOKEN IS HERE")
  File "C:\Python39\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Python39\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Python39\lib\site-packages\discord\client.py", line 651, in start
    await self.connect(reconnect=reconnect)
  File "C:\Python39\lib\site-packages\discord\client.py", line 586, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000012902E01CA0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000012902E01CA0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by rowisahub** [comment]
Got it i went to the bot page and turned on all the Privileged Gateway Intents
