### ISSUE TITLE
missing access

### ISSUE THREAD

**Issue by michaelik1** [interactions-py/interactions.py#50]
```
Ready!
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.register_all_commands() done, defined at C:\Users\usr\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\client.py:150> exception=RequestFailure('Request failed with resp: 403 | {"message": "Missing Access", "code": 50001}')>
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\client.py", line 215, in register_all_commands
    await manage_commands.add_slash_command(self._discord.user.id,
  File "C:\Users\usr\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 40, in add_slash_command
    raise RequestFailure(resp.status, await resp.text())
discord_slash.error.RequestFailure: Request failed with resp: 403 | {"message": "Missing Access", "code": 50001}
```

Used this example code from documentation:

```
import discord
from discord_slash import SlashCommand

client = discord.Client(intents=discord.Intents.all())
slash = SlashCommand(client, auto_register=True)

guild_ids = [794271205611143178] # Put your testing server ID. _This is my server ID_

@client.event
async def on_ready():
    print("Ready!")

@slash.slash(name="ping", guild_ids=guild_ids)
async def _ping(ctx):
    await ctx.send(content=f"Pong!")

client.run("my token")
```

I have given all of the permissions to the bot role on server and enabled members + presence intent. Why am i receiving this error? Btw discord.py version 1.5.1

**Comment by eunwoo1104** [comment]
Did you invite the bot with `applications.commands` scope?

**Comment by michaelik1** [comment]
> Did you invite the bot with `applications.commands` scope?

I just have invited bot from the oauth page with administrator pernissions. How i can invite it with `applications.commands` scope?

**Comment by eunwoo1104** [comment]
Go to OAuth2 page, then check like this image:
![image](https://user-images.githubusercontent.com/61371424/103470898-1c5d5080-4dbc-11eb-8ff4-d6e3fdb4f902.png)

**Comment by michaelik1** [comment]
Thank you! That worked. Now just want to ask, will the slash commands be available in so called "slash command explorer" near the icon "built-in", as now this commands appear only when i type part of their name. As i seen that custom bot commands appear in tab near "built-in", but i have no other tabs except "built-in".
```
import discord
from discord_slash import SlashCommand
from discord_slash import SlashCommandOptionType
from discord_slash.utils import manage_commands

client = discord.Client(intents=discord.Intents.all())
slash = SlashCommand(client, auto_register=True)

guild_ids = [794271205611143178] # Put your testing server ID.

@client.event
async def on_ready():
    print("Ready!")

@slash.slash(name="ping", guild_ids=guild_ids)
async def _ping(ctx):
    await ctx.send(content=f"Pong! ({client.latency*1000}ms)")

@slash.slash(name="echo", guild_ids=guild_ids, options=[manage_commands.create_option("string", "A random string.", SlashCommandOptionType.STRING, True)])
async def _echo(ctx, string):
    await ctx.send(content=string)

client.run("my token")
```
Here my slash commands explorer.
![image](https://user-images.githubusercontent.com/63803088/103471065-40a13900-4d8c-11eb-863f-f8cbd9356d1f.png)

**Comment by eunwoo1104** [comment]
Try reloading your discord client.

**Comment by michaelik1** [comment]
Thank you very much! That also helped. Would you mind if i will ask question here in case something goes wrong?

**Comment by eunwoo1104** [comment]
You can use discussions or our discord server.
