### ISSUE TITLE
[BUG] Editing Message Components causes json error

### ISSUE THREAD

**Issue by kbots-tech** [interactions-py/interactions.py#539]
**Describe the bug**
Trying to edit components in a message lead to a json embed error and not updating the buttons

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Send a message with components
4. Edit components
5. See the traceback error given in the terminal or logger file.

**What's normally expected**
When editing components buttons should update

**What actually happened**
Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "C:\Users\Keegan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\api\http.py", line 261, in request
    async with self._session.request(
  File "C:\Users\Keegan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Keegan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "C:\Users\Keegan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Embed is not JSON serializable
self.buttons[1].label = f"Page {self.page+1} of {len(self.pages)}"
self.action_row = ActionRow(components=self.buttons)
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by FayeDel** [comment]
Closing this issue as this seems to have been resolved in v4.1 stable.
