### ISSUE TITLE
Falsey data not getting passed to context [BUG] 

### ISSUE THREAD

**Issue by peaceknight05** [interactions-py/interactions.py#570]
### Describe the bug.

When running a slash command, if an argument is falsey (e.g. an empty string, or the integer 0), it causes the argument to not get passed to the command function, which causes a TypeError because the required positional argument is not given.

### List the steps.

1. Create a slash command as per usual that takes in an Integer option.
2. Run the script.
3. Run the command and pass in 0.

### What you expected.

The argument should have been passed to the function.

### What you saw.

Instead, it isn't passed to the function and I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "/Users/-/Desktop/yes-yes-bot/main.py", line 129, in <module>
    bot.start()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 109, in start
    self._loop.run_until_complete(self._ready())
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 307, in _ready
    await self._login()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 312, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 209, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 277, in _handle_connection
    self._dispatch_event(event, data)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 381, in _dispatch_event
    self._dispatch.dispatch(_name, *__args, **__kwargs)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/dispatch.py", line 37, in dispatch
    self.loop.create_task(event(*args, **kwargs))
TypeError: opt() missing 1 required positional argument: 'mode'
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by peaceknight05** [comment]
This is because of the inner working of the functions in gateway.py that get the context.

The checks done in the function `__sub_command_context` check if values are None by running `if x:` if statements, which do not run when `x` is None, or if it is a falsey value ("", 0, etc.).

Code in question (interactions/api/gateway.py line 493-494):
```py
elif _data.get("value") and _data.get("name"):
    __kwargs[_data["name"]] = _data["value"]
```

if the value of the data is falsey, `_data.get("value") and _data.get("name")` is False and kwargs is not updated.

The error above is not thrown and the command works as expected when the code is changed to the PEP 8 recommended way of checking for NoneType:

```py
elif _data.get("value") is not None and _data.get("name"):
    __kwargs[_data["name"]] = _data["value"]
```
