### ISSUE TITLE
[BUG] Slash command with "Attachment" option type gives an error

### ISSUE THREAD

**Issue by UnlucksMcGee** [interactions-py/interactions.py#575]
### Describe the bug.

When trying to accept an attachment argument in a slash command, the library gives an error:
`AttributeError: 'Attachment' object has no attribute '_client'`

### List the steps.

Example test script

```python
import interactions

if __name__ == "__main__":
    bot = interactions.Client(token="YOUR_TOKEN_HERE")
    
    @bot.command(
        name="attach",
        description="Some description",
        scope=YOUR_SCOPE_HERE,
        options= [
            interactions.Option(
                name="image",
                description="Attached image",
                type=interactions.OptionType.ATTACHMENT,
                required=True
            )
        ]
    )
    async def attach(ctx: interactions.CommandContext, image: interactions.Attachment):
        await ctx.send("Success")

    bot.start()
```

### What you expected.

I expected the bot to reply with "Success".

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "................/test.py", line 23, in <module>
    bot.start()
  File "................/python3.9/site-packages/interactions/client.py", line 109, in start
    self._loop.run_until_complete(self._ready())
  File "................/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "................/python3.9/site-packages/interactions/client.py", line 307, in _ready
    await self._login()
  File "................/python3.9/site-packages/interactions/client.py", line 312, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 209, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 277, in _handle_connection
    self._dispatch_event(event, data)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 340, in _dispatch_event
    _type[option.value]._client = self._http
AttributeError: 'Attachment' object has no attribute '_client'
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
Closing in favour of #568 .
