### ISSUE TITLE
[BUG] Unable to use ext versioning

### ISSUE THREAD

**Issue by Catalyst4222** [interactions-py/interactions.py#577]
### Describe the bug.

I am unable to use any of the versioning classes for the ext submodule (Base, Version, or VersionAuthor). This bug is not related to using them to create a setup.py file, but instead just instantiating the classes.

### List the steps.

1. Import either Base, Version, or VersionAuthor
2. Create an instance of the class
3. Either an AttributeError (Base, Verion) occurs or a TypeError (VersionAuthor) 

### What you expected.

I expected no errors to occur

### What you saw.

VersionAuthor:
```py
Traceback (most recent call last):
  File "C:\Users\X\Documents\interactions-wait-for\bot.py", line 11, in <module>
    from interactions.ext.wait_for import setup, wait_for, wait_for_component
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\wait_for\__init__.py", line 7, in <module>
    version = Version(major=1, minor=0, patch=1, author=VersionAuthor("Catalyst4", email=''))
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\version.py", line 51, in __init__
    self._hash = md5(self.__str__())
TypeError: Unicode-objects must be encoded before hashing
```
Fix: `md5(self.__str__().encode())`

Version:
```py
Traceback (most recent call last):
  File "C:\Users\X\Documents\interactions-wait-for\bot.py", line 11, in <module>
    from interactions.ext.wait_for import setup, wait_for, wait_for_component
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\wait_for\__init__.py", line 1, in <module>
    from .base import *
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\wait_for\base.py", line 34, in <module>
    version = Version(
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\version.py", line 102, in __init__
    self._authors = kwargs.get("authors", []) or kwargs.get("author", [])
AttributeError: 'Version' object has no attribute '_authors'
```
Fix: adding `'_authors'` to `__slots__`

Base:
```py
Traceback (most recent call last):
  File "C:\Users\X\Documents\interactions-wait-for\bot.py", line 11, in <module>
    from interactions.ext.wait_for import setup, wait_for, wait_for_component
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\wait_for\__init__.py", line 1, in <module>
    from .base import *
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\wait_for\base.py", line 42, in <module>
    base = Base(
  File "C:\Users\X\Documents\interactions-wait-for_venv\lib\site-packages\interactions\ext\base.py", line 68, in __init__
    self.long_description = long_description
AttributeError: 'Base' object has no attribute 'long_description'
```
Fix: adding `'long_description'` to `__slots__`

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
Flagged.
