### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType' [BUG] 

### ISSUE THREAD

**Issue by cens6r** [interactions-py/interactions.py#587]
### Describe the bug.

When trying to run the bot, a TypeError occurs.

### List the steps.

1. Create a basic bot
2. Create a command with `async def command(ctx: interactions.CommandContext)`
3. Error occurs

### What you expected.

When I create a slash command following the official documents and quick start guide, the command shouldn't raise any exceptions.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "c:\Users\User\Documents\codes\BotSkid\main.py", line 34, in <module>
    async def snipe(ctx: interactions.CommandContext):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client.py", line 599, in decorator
    [
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client.py", line 600, in <listcomp>
    self._loop.run_until_complete(self._synchronize(command))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client.py", line 223, in _synchronize
    commands: Optional[Union[dict, List[dict]]] = await self._http.get_application_commands(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\api\http.py", line 2048, in get_application_commands
    application_id = int(application_id)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
Make sure you invite the bot with the correct scope

**Comment by cens6r** [comment]
The bot was already invited with the correct scope but I was using discord.py before refactoring the code in interactions.py. Should I try reinviting the bot?

**Comment by i0bs** [comment]
Would try reinviting, yeah

**Comment by i0bs** [comment]
I believe this has been an observed behavior pattern from our support server. Because of this, we'll be flagging it down as a known bug now.

**Comment by i0bs** [comment]
We've found the issue for this and will be dealt with in the future. For people digging up this post, please make sure your bot token is valid. This error will only reproduce if your bot token is not proper. This will most commonly occur when:

- (if reading from a file) the file was read incorrectly by content or directory path
- (if putting in a token) the token has expired, been compromised or in any other form invalid.
