### ISSUE TITLE
[BUG] Embed only accepting dictionaries as attributes

### ISSUE THREAD

**Issue by mAxYoLo01** [interactions-py/interactions.py#657]
### Describe the bug.

When trying to instantiate an embed using some custom fields such as:
```py
embed = interactions.Embed(
  video=interactions.EmbedImageStruct(url=URL)
)
```
the code will give back an error:
```
Traceback (most recent call last):
  File ".\launch.py", line 70, in test
    embed = interactions.Embed(
  File ".\interactions\api\models\message.py", line 1076, in __init__
    EmbedImageStruct(**self.video)
TypeError: interactions.api.models.message.EmbedImageStruct() argument after ** must be a mapping, not EmbedImageStruct
```

The only way to solve it is to add `._json` to each Embed custom class.

### List the steps.

Try to create an Embed using EmbedImageStruct or EmbedProvider, etc...

### What you expected.

.

### What you saw.

.

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by mAxYoLo01** [comment]
Closing due to #658 being merged
