### ISSUE TITLE
[BUG] kwargs modified during iteration in the DictSerializerMixin

### ISSUE THREAD

**Issue by V3ntus** [interactions-py/interactions.py#683]
### Describe the bug.

This seems to be invoked inconsistently and I'm not quite sure what triggers it

### List the steps.

- This first originated from a simple `ctx.send` with an embed

### What you expected.

Normal operation

### What you saw.

```py
future: <Task finished name='Task-12' coro=<Weather.get_weather() done, defined at /Users/ventus/GitRepos/bamboos-sidekick/cogs/weather.py:137> exception=RuntimeError('dictionary changed size during iteration')>
Traceback (most recent call last):
  File "/Users/ventus/GitRepos/bamboos-sidekick/cogs/weather.py", line 159, in get_weather
    await ctx.send(embeds=Embed(
  File "/Users/ventus/GitRepos/bamboos-sidekick/interactions/api/models/message.py", line 1028, in __init__
    super().__init__(**kwargs)
  File "/Users/ventus/GitRepos/bamboos-sidekick/interactions/api/models/misc.py", line 39, in __init__
    for key in kwargs:
RuntimeError: dictionary changed size during iteration
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
I would not be surprised if its the fault of `__setattr__`

(I swear I never encountered this while testing)

**Comment by V3ntus** [comment]
It seems like EmbedFields are converting from objects to json during iteration somehow?
```py
DEBUG:mixin:{'title': 'Weather for xxx', 'color': 16756224, 'fields': [<interactions.api.models.message.EmbedField object at 0x7fd1a6350f40>, <interactions.api.models.message.EmbedField object at 0x7fd1a6350ea0>, <interactions.api.models.message.EmbedField object at 0x7fd1a636c040>, <interactions.api.models.message.EmbedField object at 0x7fd1a636c2c0>, <interactions.api.models.message.EmbedField object at 0x7fd1a636c220>, <interactions.api.models.message.EmbedField object at 0x7fd1a636c1d0>, <interactions.api.models.message.EmbedField object at 0x7fd1a636c0e0>], 'timestamp': None}
CRITICAL:mixin:HIT
DEBUG:mixin:{'title': 'Weather for xxx', 'color': 16756224, 'fields': [{'name': 'Current Temperature:', 'value': '77.9°F', 'inline': True}, {'name': 'Feels Like:', 'value': '78.3°F', 'inline': True}, {'name': 'High / Low:', 'value': '78.7°F / 75.7°F', 'inline': True}, {'name': 'Humidity:', 'value': '62%', 'inline': True}, {'name': 'Wind:', 'value': '187/S at 18.6mph', 'inline': True}, {'name': 'Sunrise / Sunset:', 'value': '07:13:43 / 19:39:13', 'inline': True}, {'name': 'Clouds:', 'value': 'overcast clouds', 'inline': True}]}
```

Using this code to test: `api/models/misc.py:40-53`
```py
log.debug(kwargs)
try:
    for key in kwargs:
        if key in self.__slots__ if hasattr(self, "__slots__") else True:
            # else case if the mixin is used outside of this library and/or SDK.
            setattr(self, key, kwargs[key])
        else:
            log.info(
                f"Attribute {key} is missing from the {self.__class__.__name__} data model, skipping."
            )
            # work on message printout? Effective, but I think it should be a little bit more friendly
            # towards end users
except: # noqa
    log.critical("HIT")
    log.debug(kwargs)
```

**Comment by sillyElvy** [comment]
y e a h

`__setattr__` in the embed class

but again, when I tested it worked fine

**Comment by V3ntus** [comment]
> but again, when I tested it worked fine

This is an edge case. Another embed (with a single field) works

**Comment by sillyElvy** [comment]
I had multiple fields tho
