### ISSUE TITLE
[BUG] Cannot unload cog if class name is equal to file name

### ISSUE THREAD

**Issue by anirudhnara** [interactions-py/interactions.py#711]
### Describe the bug.

When I tried to reload or remove a cog using a command, I got a RecursionError. So I looked in the code and I found this:
![image](https://user-images.githubusercontent.com/68088818/161906351-c55b4e81-aad7-498a-9ca9-e7e580c029b1.png)

### List the steps.

1. Do `bot.remove("cog_name")` or `bot.reload("cog_name")`.
2. Execute the code or the command.
3. See the error.

### What you expected.

I expected the code to reload the cog and tell me that the cog has been reloaded in Discord.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "c:\Users\olafm\Documents\Coding\Python\Bots\Cryptocord\bot.py", line 24, in reload
    bot.reload(cog)
  File "C:\Users\olafm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\client.py", line 1006, in reload
    self.remove(name, package)
  File "C:\Users\olafm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\client.py", line 973, in remove
    self.remove(name)
  File "C:\Users\olafm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\client.py", line 973, in remove
    self.remove(name)
  File "C:\Users\olafm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\client.py", line 973, in remove
    self.remove(name)
  [Previous line repeated 984 more times]
  File "C:\Users\olafm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\interactions\client.py", line 953, in remove
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Catalyst4222** [comment]
This error happens if both the file name and the class name are the same. For now, you can just rename either the file or class until a fix gets pushed

**Comment by AstreaTSS** [comment]
Renamed to narrow the scope of this bug.

**Comment by Catalyst4222** [comment]
Closing this issue as it appears to be resolved in the stable branch
