### ISSUE TITLE
[BUG] KeyError, Bot cannot start

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#738]
### Describe the bug.

interactions.py prints a KeyError just by starting it

### List the steps.

I tested it in multiple environments, but I can't launch only this bot (other bots work fine).
This issue is seen on 4.1.1 Beta 2 and 4.1.1 RC1 and not on 4.1.0 and 4.1.1 Beta 1

Console Log↓
```py
import interactions
bot = interactions.Client(token="")
bot.start()
```

### What you expected.

I hope Bot starts.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```py
>>> import interactions
>>> bot = interactions.Client(token="", disable_sync=False)
>>> bot.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/client/bot.py", line 115, in start
    self._loop.run_until_complete(self._ready())
  File "/home/xs905136/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/client/bot.py", line 326, in _ready
    await self._login()
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/client/bot.py", line 331, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 189, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 257, in _handle_connection
    self._dispatch_event(event, data)
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 353, in _dispatch_event
    self._dispatch.dispatch(f"on_{name}", __obj(**data))  # noqa
  File "/home/xs905136/miniconda3/lib/python3.9/site-packages/interactions/api/models/guild.py", line 325, in __init__
    and self._client.cache.self_guilds.values[str(self.id)].members
KeyError: '889041902773604362'
>>>
```

### What version of the library did you use?

stable

### Version specification

4.1.1 Beta2 and 4.1.1 RC1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by mAxYoLo01** [comment]
Is `889041902773604362` the bot token you set? If yes, then this is a false one, you have mixed the client ID and the secret client. Try to put your bot's secret ID instead

**Comment by ghost** [comment]
No, I don't think this error will be output even if you write the client ID here.
As I said it works on other bots, it's not mixed.
It works with "4.1.1 Beta1" and "4.1.0" in the first place. The code is correct.
The same code doesn't work if you change the version.

**Comment by AstreaTSS** [comment]
This is an odd problem. I think it may be worth looking at the code in question [piece of code responsible](https://github.com/interactions-py/library/blob/1d3ec28aa5d8bd1b8cc6c52c15960e118b6a8cc8/interactions/api/models/guild.py#L321-L326):

```python
if (
    not self.members
    and self._client
    and len(self._client.cache.self_guilds.view) > 1
    and self._client.cache.self_guilds.values[str(self.id)].members
):
```

Theoretically:
- Discord has a `GUILD_CREATE` event to get the guild data *after* the `READY` event. Before this "guild creation", I don't *think* `interactions.py` attempts to store the unavailable guild that is gotten before `READY` in cache, though I could be wrong. If I am, everything from here on out is inaccurate.
- A bot receives a `GUILD_UPDATE` event or the like, maybe? Weird to get it *before* the create event but hey, Discord. Or maybe a user is getting a guild from a message/context? That would also trigger it. Point is, if there's a point where a `Guild` is being created while *also* passing in `_client`, then this bug is possible.
- `self.members` is `None` because that's never given except on `GUILD_CREATE`.
- The first two checks pass.
- The third one *can* pass if *some* guilds have been "lazy loaded" and have had their `GUILD_CREATE` events passed.
- However, `interactions.py` has *not* received the `GUILD_CREATE` event for the guild we are currently trying to create. This means it is not in the cache as a value.
- Error as seen above.

Regardless, the way we are doing this right now is pretty naive. Checking if `self_guilds` even has the guild stored in it first would be a better idea.

**Comment by i0bs** [comment]
Extending on this list, `GUILD_CREATE` is an asynchronously independent event from the Gateway's `READY` state, meaning this can fire around the same time that the Gateway declares the WebSocket client "ready," during or after. Bricking the condition by ensuring any set size of `self_guilds` will instantly make this fail first, and then the rest of these points coming into play.

**Comment by ghost** [comment]
Thank you for your quick response.
My problem is completely solved.
