### ISSUE TITLE
[BUG] message and code are swapped in LibraryException

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#896]
### Describe the bug.

in `LibraryException` this is the `__init__`:
```py
def __init__(self, message: str = None, code: int = 0, severity: int = 0, **kwargs):
```
however, the library uses errors like:
```py
raise LibraryException(11, message="Your command must have a name.")
```
which when tried in a terminal results in
```py
>>> raise LibraryException(11, message="Your command must have a name.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got multiple values for argument 'message'
```
so the `__init__` should instead be
```py
def __init__(self, code: int = 0, message: str = None, severity: int = 0, **kwargs):
```

### List the steps.

```py
>>> from interactions import LibraryException 
>>> raise LibraryException(11, message="Your command must have a name.") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got multiple values for argument 'message'
```

### What you expected.

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
interactions.api.error.LibraryException: An error occurred:
Your command must have a name., with code '11' and severity '0'
```

### What you saw.

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got multiple values for argument 'message'
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
"intended feature 🤓"

jokes aside this is a breaking bug when an interaction exception occurs anywhere as our running process only throws it and keeps the loop ongoing
