### ISSUE TITLE
TypeError: on_slash() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by echan00** [interactions-py/interactions.py#91]
discord-py-slash-command==1.0.9 (hotfix-command-register branch)

I just added a new command to my bot:

```
{
	"id": "XXX", 
	"application_id": "YYY", 
	"name": "help", 
	"description": "See Game Basics", 
	"version": "807752974251065344", 
	"options": [
		{
		"type": 6, 
		"name": "user", 
		"description": "User to send help tutorial to"
		}
	]
}
```

Since the option is not required, everything works fine with no options. But when I include a user as specified in the options, I get the following error.

```
An exception has occurred while executing command `help`:
Traceback (most recent call last):
  File "/Users/xxx/Workspace/discord-bot/venv/lib/python3.7/site-packages/discord_slash/client.py", line 725, in on_socket_response
    await selected_cmd.invoke(ctx, *args)
  File "/Users/xxx/Workspace/discord-bot/venv/lib/python3.7/site-packages/discord_slash/model.py", line 49, in invoke
    return await self.func(*args)
TypeError: on_slash() takes 1 positional argument but 2 were given
```

**Comment by eunwoo1104** [comment]
Add another arg at your command coroutine.
For example:
```py
@slash.slash(...)
async def help(ctx, user=None):
    ...
```

**Comment by ghost** [comment]
..why is this still open...

**Comment by eunwoo1104** [comment]
Closing due to no response.
