### ISSUE TITLE
[BUG] OptionType.MENTIONABLE tries mapping NoneType resulting in crashing the bot

### ISSUE THREAD

**Issue by Quarlie** [interactions-py/interactions.py#914]
### Describe the bug.

Trying to use the OptionType.MENTIONABLE type for an Option for a slash commands results in a crash and the bot shutting down

At lib\site-packages\interactions\api\gateway\client.py, line 567, it tries mapping both the Role and User for OptionType.MENTIONABLE, even though only one of them gets mentioned. Because only one is always mentioned, one of the two will always be a NoneType, which tries to get mapped, resulting in a crash and the bot shutting down.

### List the steps.

1. Create a simple slash command
2. Make an option
3. Make the type of the option (interactions.)OptionType.MENTIONABLE
4. Start the bot after finishing the command
5. Execute the slash command in discord

The bot will respong with "The application did not respond" and the Traceback error below is given in the Python terminal, which finally shuts down the bot entirely.

### What you expected.

For the command to be simply executed without crashing.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "C:\Users\HP\source\repos\GeezerBot\main.py", line 80, in <module>
    run()
  File "C:\Users\HP\source\repos\GeezerBot\main.py", line 77, in run
    client.start()
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\client\bot.py", line 134, in start
    raise e from e
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\client\bot.py", line 132, in start
    self._loop.run_until_complete(self._ready())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\client\bot.py", line 390, in _ready
    await self._login()
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\client\bot.py", line 395, in _login
    await self._websocket._establish_connection(self._shards, self._presence)
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\api\gateway\client.py", line 196, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\api\gateway\client.py", line 264, in _handle_connection
    self._dispatch_event(event, data)
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\api\gateway\client.py", line 294, in _dispatch_event
    _type = self.__option_type_context(
  File "C:\Users\HP\source\repos\GeezerBot\TestCodes\lib\site-packages\interactions\api\gateway\client.py", line 567, in __option_type_context
    _resolved = {
TypeError: 'NoneType' object is not a mapping

Process finished with exit code 1
```

### What version of the library did you use?

unstable

### Version specification

4.3.0b1

### Code of Conduct

- [x] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
This issue should've been fixed now
