### ISSUE TITLE
'channel' is not present in context if it is DM channel

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#93]
My code:
```py
async for msg in ctx.channel.history(limit=amount):
        await msg.delete()
```
And when I run this command, exception throws: NoneType object has no attribute 'history'
As you can understand from this exception, it is tells that context not presents channel in direct messages channel.
Why?

**Comment by eunwoo1104** [comment]
That is weird. It works for me. `type(ctx.channel)` returns `<class 'discord.channel.DMChannel'>` for me, which means its not None.
Any more details like intents, etc?

**Comment by ghost** [comment]
> That is weird. It works for me. `type(ctx.channel)` returns `<class 'discord.channel.DMChannel'>` for me, which means its not None.
> Any more details like intents, etc?

All intents are enabled. Also, full command code is:
```py
@slash.slash()
async def очистить(ctx: ctx, количество: int=20):
    """
    Очистка сообщений. *Только для Флеша и Альфы*
    """
    await ctx.ack(eat=True)

    if ctx.guild:
        if ctx.author.guild_permissions.manage_messages:
            purged = await ctx.channel.purge(limit=количество)
            await ctx.send(f"Очищено {len(purged)} сообщений!", delete_after=2.0)
        else:
            await ctx.send("Вы не имеете прав на использование данной команды!", hidden=True)

    else:
        async for msg in ctx.channel.history(limit=количество):
            await msg.delete()
```
In guild, it is works, but not in DMs. Using version from github, discord.py stable, from pypi.

**Comment by ghost** [comment]
Also:
Jishaku output
```py
Jishaku v1.20.0, discord.py 1.5.1, Python 3.8.6 (default, Dec 18 2020, 05:24:40) [GCC 8.3.0] on linux
Module was loaded 27 seconds ago, cog was loaded 25 seconds ago.

This bot is automatically sharded and can see 1 guild(s) and 2 user(s).
Message cache capped at 1000, presence intent is enabled and members intent is enabled.
Average websocket latency: 130.38ms
```
And new exception appearing now:
```
An exception has occurred while executing command `очистить`:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord_slash/client.py", line 644, in invoke_command
    await func.invoke(ctx, **args)
  File "/home/container/.local/lib/python3.8/site-packages/discord_slash/model.py", line 49, in invoke
    return await self.func(*args, **kwargs)
  File "robot-src/main.py", line 61, in очистить
    await msg.delete()
  File "/home/container/.local/lib/python3.8/site-packages/discord/message.py", line 801, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/container/.local/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50003): Cannot execute action on a DM channel
```

**Comment by ghost** [comment]
I will close issue and ask for help in d.py guild
